FROM discoverd-ruby-base

# Add discoverd-ruby
ADD . /discoverd-ruby

# Run etcd, discoverd then the integration tests
CMD bash -c "/usr/local/bin/etcd >/dev/null &" && \
    bash -c "/go/bin/discoverd >/dev/null &" && \
    bash -c "cd /discoverd-ruby && bundle exec ruby -Ilib:test test/integration/test_*.rb"
