FROM discoverd-ruby-base

# Add discoverd-ruby
ADD . /discoverd-ruby

# Run etcd, discoverd then the integration tests
CMD bash -c "cd /discoverd-ruby && PATH=\${PATH}:/go/bin bundle exec ruby -Ilib:test test/integration/test_*.rb"
